:global:
  :emailfix:
    :file: config/emailfix.yaml
  :list:
    :file: list.yaml
  :cctlds: [ac, ad, ae, af, ag, ai, al, am, an, ao, aq, ar, as, at, au, aw, ax, az, ba, bb, bd, be, bf, bg, bh, bi, bj, bm, bn, bo, br, bs, bt, bv, bw, by, bz, ca, cc, cd, cf, cg, ch, ci, ck, cl, cm, cn, co, cr, cu, cv, cx, cy, cz, de, dj, dk, dm, do, dz, ec, ee, eg, er, es, et, eu, fi, fj, fk, fm, fo, fr, ga, gb, gd, ge, gf, gg, gh, gi, gl, gm, gn, gp, gq, gr, gs, gt, gu, gw, gy, hk, hm, hn, hr, ht, hu, id, ie, il, im, in, io, iq, ir, is, it, je, jm, jo, jp, ke, kg, kh, ki, km, kn, kp, kr, kw, ky, kz, la, lb, lc, li, lk, lr, ls, lt, lu, lv, ly, ma, mc, md, me, mg, mh, mk, ml, mm, mn, mo, mp, mq, mr, ms, mt, mu, mv, mw, mx, my, mz, na, nc, ne, nf, ng, ni, nl, no, np, nr, nu, nz, om, pa, pe, pf, pg, ph, pk, pl, pm, pn, pr, ps, pt, pw, py, qa, re, ro, rs, ru, rw, sa, sb, sc, sd, se, sg, sh, si, sj, sk, sl, sm, sn, so, sr, st, su, sv, sy, sz, tc, td, tf, tg, th, tj, tk, tl, tm, tn, to, tp, tr, tt, tv, tw, tz, ua, ug, uk, us, uy, uz, va, vc, ve, vg, vi, vn, vu, wf, ws, ye, yt, za, zm, zw]
  :gtlds: [aero, arpa, asia, biz, cat, com, coop, edu, gov, info, int, jobs, mil, mobi, museum, name, net, org, pro, tel, travel, xxx]

:db:
  :current: :sqlite3
  :sqlite3:
    :adapter: sqlite3
    :database: /home/ram/git.sqlite3
  :pg:
    :adapter: postgresql
    :database: git
    :username: rafael
    :password: 
    :host: localhost

:servers:


  :linux:
    :host: git.kernel.org
    :ip: 149.20.4.72
    :data:
      :dir:
      - data/linux/
      - 
      :gitlog: /home/rafael/linux.gitlog
      :csv: data/linux.dat
    :git:
      :url:
      - git://149.20.4.72/pub/scm/
      -
    :description:
      :url:
      - http://149.20.4.72/?a=rss;p=
      -
      :find:
        :xpath: /rss/channel/description
        :nslist:
    :origin:
      :default: .
      :regexp:
    :list:
      :url: http://149.20.4.72/?a=project_index
      :regexp: ^[^\s]*
      :only:
      - linux/kernel/git/torvalds/linux.git


  :gnome:
    :host: git.gnome.org
    :ip: 209.132.180.173
    :data:
      :dir:
      - data/gnome/
      - .git
      :gitlog: /home/rafael/gnome.gitlog
      :csv: data/gnome.dat
    :git:
      :url:
      - git://209.132.180.173/
      -
    :description:
      :url:
      - http://209.132.180.173/browse/
      - /atom
      :find:
        :xpath: //ns:subtitle
        :nslist: ns:http://www.w3.org/2005/Atom
    :origin:
      :default: .
      :regexp:
    :list:
      :url: http://209.132.180.173/repositories.txt
      :regexp: ^[^\s]*


  :android:
    :host: android.git.kernel.org
    :ip: 149.20.4.77
    :data:
      :dir:
      - data/android/
      - 
      :gitlog: /home/rafael/android.gitlog
      :csv: data/android.dat
    :git:
      :url:
      - git://149.20.4.77/
      -
    :description:
      :url:
      - http://149.20.4.77/?a=rss;p=
      - 
      :find:
        :xpath: /rss/channel/description
        :nslist: 
    :origin:
      :default: android
      :regexp: ^(platform/external|kernel)
    :list:
      :url: http://149.20.4.77/?a=project_index
      :regexp: ^[^\s]*
      :deny:
      - kernel/experimental.git
      - kernel/linux-2.6.git
    :instances:
      kernel/common.git:
        :dir: data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/common/android-3.0
        :fork: true
      kernel/msm.git:
        :dir: data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/msm/android-msm-2.6.35
        :fork: true
      kernel/omap.git:
        :dir: data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/omap/android-omap-3.0
        :fork: true
      kernel/qemu.git:
        :dir: data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/qemu/android-goldfish-2.6.29
        :fork: true
      kernel/samsung.git:
        :dir: data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/samsung/android-samsung-2.6.35
        :fork: true
      kernel/tegra.git:
        :dir: data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/tegra/android-tegra-2.6.39
        :fork: true

