:db:
  :commits:
    :adapter: sqlite3
    :database: /home/ram/commits.sqlite3
  :crunchbase:
    :adapter: sqlite3
    :database: /home/ram/cb.sqlite3

:servers:
  :linux:
    :host: git.kernel.org
    :ip: 149.20.4.72
    :data:
      :dir:
      - /media/attach/data/git/source/linux/
      - 
      :csv: /media/attach/data/git/working/linux.dat
    :git:
      :url:
      - git://149.20.4.72/pub/scm/
      -
    :description:
      :url:
      - http://149.20.4.72/?a=rss;p=
      -
      :find:
        :xpath: /rss/channel/description
        :nslist:
    :origin:
      :default: .
      :regexp: '^$'
    :list:
      :url: http://149.20.4.72/?a=project_index
      :regexp: ^[^\s]*
      :only:
      - linux/kernel/git/torvalds/linux.git

  :gnome:
    :host: git.gnome.org
    :ip: 209.132.180.173
    :data:
      :dir:
      - /media/attach/data/git/source/gnome/
      - .git
      :csv: /media/attach/data/git/working/gnome.dat
    :git:
      :url:
      - git://209.132.180.173/
      -
    :description:
      :url:
      - http://209.132.180.173/browse/
      - /atom
      :find:
        :xpath: //ns:subtitle
        :nslist: ns:http://www.w3.org/2005/Atom
    :origin:
      :default: .
      :regexp: '^$'
    :list:
      :url: http://209.132.180.173/repositories.txt
      :regexp: ^[^\s]*

  :android:
    :host: android.git.kernel.org
    :ip: 149.20.4.77
    :data:
      :dir:
      - /media/attach/data/git/source/android/
      - 
      :csv: /media/attach/data/git/working/android.dat
    :git:
      :url:
      - git://149.20.4.77/
      -
    :description:
      :url:
      - http://149.20.4.77/?a=rss;p=
      - 
      :find:
        :xpath: /rss/channel/description
        :nslist: 
    :origin:
      :default: android
      :regexp: ^(platform/external|kernel)
    :list:
      :url: http://149.20.4.77/?a=project_index
      :regexp: ^[^\s]*
      :deny:
      - kernel/experimental.git
      - kernel/linux-2.6.git
    :instances:
      kernel/common.git:
        :dir: /home/rafael/media/git-data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/common/android-3.0
        :fork: true
      kernel/msm.git:
        :dir: /home/rafael/media/git-data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/msm/android-msm-2.6.35
        :fork: true
      kernel/omap.git:
        :dir: /home/rafael/media/git-data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/omap/android-omap-3.0
        :fork: true
      kernel/qemu.git:
        :dir: /home/rafael/media/git-data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/qemu/android-goldfish-2.6.29
        :fork: true
      kernel/samsung.git:
        :dir: /home/rafael/media/git-data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/samsung/android-samsung-2.6.35
        :fork: true
      kernel/tegra.git:
        :dir: /home/rafael/media/git-data/linux/linux/kernel/git/torvalds/linux.git
        :range: ..remotes/tegra/android-tegra-2.6.39
        :fork: true

:conflicts: conflicts.yaml
:emailfix: emailfix.yaml
:list: list.yaml

