:host: android.git.kernel.org
:ip: 149.20.4.77
:data:
  :dir:
  - data/android/
  - 
:git:
  :url:
  - git://149.20.4.77/
  -
:description:
  :url:
  - http://149.20.4.77/?a=rss;p=
  - 
  :find:
    :xpath: /rss/channel/description
    :nslist: 
:list:
  :url: http://149.20.4.77/?a=project_index
  :regexp: ^[^\s]*
  :file: config/list-android.yaml
:instances:
  kernel/common.git:
    :dir: data/linux/linux/kernel/git/torvalds/linux.git
    :range: ..remotes/common/android-3.0
    :fork: true
  kernel/msm.git:
    :dir: data/linux/linux/kernel/git/torvalds/linux.git
    :range: ..remotes/msm/android-msm-2.6.35
    :fork: true
  kernel/omap.git:
    :dir: data/linux/linux/kernel/git/torvalds/linux.git
    :range: ..remotes/omap/android-omap-3.0
    :fork: true
  kernel/qemu.git:
    :dir: data/linux/linux/kernel/git/torvalds/linux.git
    :range: ..remotes/qemu/android-goldfish-2.6.29
    :fork: true
  kernel/samsung.git:
    :dir: data/linux/linux/kernel/git/torvalds/linux.git
    :range: ..remotes/samsung/android-samsung-2.6.35
    :fork: true
  kernel/tegra.git:
    :dir: data/linux/linux/kernel/git/torvalds/linux.git
    :range: ..remotes/tegra/android-tegra-2.6.39
    :fork: true

