:host: git.kernel.org
:ip: 149.20.4.72
:data:
  :dir:
  - data/linux/
  - 
:git:
  :url:
  - git://149.20.4.72/pub/scm/
  -
:description:
  :url:
  - http://149.20.4.72/?a=rss;p=
  -
  :find:
    :xpath: /rss/channel/description
    :nslist:
:list:
  :url: http://149.20.4.72/?a=project_index
  :regexp: ^[^\s]*
  :file: config/list-linux.yaml
  :deny:
  - 
  :only:
  - linux/kernel/git/torvalds/linux.git
